---
- name: activate Gzip
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '644'
  notify: restart nginx

- name: Remove default nginx vhost config file
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: configure vhost
  template:
    src: ./templates/vhost.conf.j2
    dest: /etc/nginx/sites-available/vhost.conf
    owner: ubuntu
    group: ubuntu
    mode: '644'
  notify: restart nginx

- name: Create symbolic link 
  file:
    src: "/etc/nginx/sites-available/vhost.conf"
    dest: "/etc/nginx/sites-enabled/vhost.conf"
    state: link
  notify: restart nginx