---
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install Nginx
  apt: 
    name: nginx 
    state: present
  notify: restart nginx

- name: Make sure nginx unit is running
  systemd:
    state: started
    name: nginx