---
- name: create a new user
  mysql_user:  
    name: "{{ mysql_user }}"  
    host: localhost
    password: "{{ mysql_password }}"  
    check_implicit_admin: yes  
    priv: "{{ database_name }}.*:ALL,GRANT"

- name: create a new database  
  mysql_db: 
    name: "{{ database_name }}" 
    state: present 